name: hyp3-gather-landsat
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - gdal>=3
  - pip
  # For packaging, and testing
  - setuptools_scm
  - pystac-client
  - pytest
  - pytest-console-scripts
  - pytest-cov
  # For running
  - hyp3lib>=3,<5
  - owslib==0.28.1
  # TODO: insert conda-forge dependencies as list here
  - pip:
      - -r requirements-static.txt
