name: hyp3-gather-landsat
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10,<3.13
  - gdal==3.11.0
  - pip
  # For packaging, and testing
  - setuptools_scm
  - pystac-client
  - pytest
  - pytest-console-scripts
  - pytest-cov
  # For running
  - hyp3lib>=3,<5
  - owslib==0.34.1
  # For plotting
  - folium
  - jupyterlab
  # TODO: insert conda-forge dependencies as list here
  - pip:
      - -r requirements-static.txt
